FROM bertoost/nginx:1.23.2

LABEL maintainer="Bert Oost <hello@bertoost.com>"

# Remove any parent placeholder files from NginX config
RUN find /etc/nginx/conf.d/ -name "*.placeholder" -type f -delete

COPY conf.d/dev/php73.conf /etc/nginx/conf.d/php73.placeholder
COPY conf.d/dev/php74.conf /etc/nginx/conf.d/php74.placeholder
COPY conf.d/dev/php80.conf /etc/nginx/conf.d/php80.placeholder
COPY conf.d/dev/php81.conf /etc/nginx/conf.d/php81.placeholder